[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ss_flow = "8K8ELAz6Q5uvNwQz1iYqn8BnLU1Lf1LFghCTSnBvHAF6"

[programs.devnet]
ss_flow = "8K8ELAz6Q5uvNwQz1iYqn8BnLU1Lf1LFghCTSnBvHAF6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "home/ec2-user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
