[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ss_flow = "AsPzpJCRrzHCqZnV3LyykMgLKEBt4oB87XLPC1e15dSp"

[programs.devnet]
ss_flow = "AsPzpJCRrzHCqZnV3LyykMgLKEBt4oB87XLPC1e15dSp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "home/ec2-user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
